const fs = require('fs');
const path = require('path');

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderMetric(label, value) {
  return `
    <div class="metric">
      <span>${escapeHtml(label)}</span>
      <strong>${escapeHtml(value)}</strong>
    </div>
  `;
}

function renderCard(card) {
  const metricsHtml = Object.entries(card.metrics || {})
    .map(([label, value]) => renderMetric(label, value))
    .join('');

  return `
    <div class="card">
      <h3>${escapeHtml(card.title)}</h3>
      ${metricsHtml}
    </div>
  `;
}

function renderSection(section) {
  const cardsHtml = (section.cards || []).map(renderCard).join('');

  return `
    <section>
      <h2>${escapeHtml(section.title)}</h2>
      <div class="cards">
        ${cardsHtml}
      </div>
    </section>
  `;
}

async function generateCustomHtmlReport({ title, fileName, sections }) {
  const reportsDir = path.join(process.cwd(), 'test-results', 'custom-reports');

  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background: #f5f6fa;
      color: #1f2937;
    }

    header {
      background: linear-gradient(135deg, #7b1113, #1f2937);
      color: white;
      padding: 28px 40px;
    }

    header h1 {
      margin: 0;
      font-size: 30px;
    }

    header p {
      margin-top: 8px;
      opacity: 0.85;
    }

    main {
      padding: 32px 40px;
    }

    section {
      margin-bottom: 34px;
    }

    h2 {
      font-size: 22px;
      margin-bottom: 18px;
    }

    .cards {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
      gap: 20px;
    }

    .card {
      background: white;
      border-radius: 16px;
      padding: 22px;
      box-shadow: 0 8px 24px rgba(0,0,0,0.08);
      border-top: 5px solid #7b1113;
    }

    .card h3 {
      margin-top: 0;
      margin-bottom: 18px;
      font-size: 19px;
    }

    .metric {
      display: flex;
      justify-content: space-between;
      padding: 12px 0;
      border-bottom: 1px solid #edf0f5;
      font-size: 15px;
    }

    .metric:last-child {
      border-bottom: none;
    }

    .metric strong {
      font-size: 18px;
    }

    footer {
      padding: 18px 40px;
      color: #6b7280;
      font-size: 13px;
    }
  </style>
</head>
<body>
  <header>
    <h1>${escapeHtml(title)}</h1>
    <p>Generated on ${new Date().toLocaleString()}</p>
  </header>

  <main>
    ${(sections || []).map(renderSection).join('')}
  </main>

  <footer>
    Generated by Playwright Custom HTML Reporter
  </footer>
</body>
</html>
`;

  const filePath = path.join(reportsDir, fileName);
  fs.writeFileSync(filePath, html, 'utf8');

  console.log(`Custom HTML report generated: ${filePath}`);

  return filePath;
}

module.exports = { generateCustomHtmlReport };